version: "3.9"
services:
  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE='iron'
    volumes:
      - ./create_index.js:/tmp/create_index.js
      - ./init_mongo.sh:/docker-entrypoint-initdb.d/init_mongo.sh
    ports:
      - 27017:27017
    restart: always
  backend:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db